spring:
  profiles:
    active:
      - dev
server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: provider-8001
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
 
---
spring:
  profiles: dev
  application:
    name: provider-dev

---
spring:
  profiles: test
  application:
    name: provider-test

