spring:
  application:
    name: provider
  profiles:
    active:
      - test
#info信息
info:
  app:
    name: provider-8002
  company:
    name: www.xxx.com
  build:
    artifactId: ${project.artifactId}
    version: ${project.version}
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: provider-8002
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
 
---
spring:
  profiles: dev
  application:
    name: provider-dev

---
spring:
  profiles: test
  application:
    name: provider-test

