spring:
  profiles:
    active:
      - dev
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: provider-8002
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
text: abcd================
 
---
spring:
  profiles: dev
  application:
    name: provider-dev

---
spring:
  profiles: test
  application:
    name: provider-test

