spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: config-dev01
server:
  port: 8081

---
spring:
  profiles: test
  application:
    name: config-test01
server:
  port: 8082