spring:
  profiles:
    active:
      - dev
#info信息
info:
  app:
    name: config-client-8081
  company:
    name: www.xxx.com
  build:
    artifactId: ${project.artifactId}
    version: ${project.version}
    
---
spring:
  profiles: dev
  application:
    name: config-dev12
server:
  port: 8081

---
spring:
  profiles: test
  application:
    name: config-test
server:
  port: 8082
